### ISSUE TITLE
higher speeds

### ISSUE THREAD

**Issue by nerdralph** [wagiminator/ATtiny13-TinyOLEDdemo#1]
I've found the SSD1306 can handle well in excess of 400kHz.  It was at least 650kHz, and maybe as much as 1MHz from what I can recall.
However if you want to stick to the spec of 400kHz, you could do the shift `data <<= 1` between SCL_HI and SCL_LO.  That would make the high period 3 clocks (1 for lsr + 2 for sbi), and at 4.8MHz that's 625ns.  For the ACK bit SCL toggle, add `asm ("nop")` to make it 3 cycles.

**Comment by wagiminator** [comment]
Thank you for this helpful tip! I implemented that right away.
