### ISSUE TITLE
use LTO to save flash

### ISSUE THREAD

**Issue by nerdralph** [wagiminator/ATtiny13-TinyOLEDdemo#2]
add -flto to reduce the target binary flash size.
https://github.com/wagiminator/ATtiny13-TinyOLEDdemo/blob/main/software/TinyOLEDdemo_text/makefile

If you aren't familiar with LTO, I wrote a blog post about it several years ago.
http://nerdralph.blogspot.com/2014/04/gcc-link-time-optimization-can-fix-bad.html

**Comment by wagiminator** [comment]
Thank you for this helpful tip! I implemented that right away.
