### ISSUE TITLE
consider a smaller font

### ISSUE THREAD

**Issue by nerdralph** [wagiminator/ATtiny13-TinyOLEDdemo#3]
Since 1/3 of the code for the text example is the font bitmap, consider using a smaller font.   I think a 4x7 font is still very readable, even more so when limited to upper case like you already do.  That would save more than 64 bytes, as a 4x7 font would allow you calculate the offset in a uint8_t instead of requiring a uint16_t.
At the extreme, if you can tolerate an unusual font style, you could go down to 3x5.
https://hackaday.io/project/6309-vga-graphics-over-spi-and-serial-vgatonic/log/20759-a-tiny-4x6-pixel-font-that-will-fit-on-almost-any-microcontroller-license-mit
Personally I find such a small font unreadable without magnification on a 0.96" 128x32 OLED.  But then I'm an old guy, and 15 years ago I didn't have any trouble reading such small text.

**Comment by wagiminator** [comment]
Of course you are right. That's just one example of where the memory is enough in the end. In real world applications, of course, you have to limit yourself.
