### ISSUE TITLE
smaller OLED init sequence

### ISSUE THREAD

**Issue by nerdralph** [wagiminator/ATtiny13-TinyOLEDdemo#4]
I was able to use a smaller init sequence, after reading through the ssd1306 datasheet for what the reset value of the registers are, and removing duplication of those in the init sequence..  I didn't finish testing the code; I forget if this init sequence properly enables all 4 rows, so it may require tweaking.
https://github.com/nerdralph/nerdralph/blob/master/avr/ssd1306.cpp#L17

**Comment by wagiminator** [comment]
It didn't quite work, but I was able to throw out a few bytes.
